### ISSUE TITLE
Error: Config file doesn't exist

### ISSUE THREAD

**Issue by Schikro** [JoYoungjoo/SC-FEGAN#11]
First, my apologies: I am extremely new to working with Python. Let me give you a quick overview of what I did:

0) Run Windows 10 (64x) with Python 3.7.2 (64bit)
1) Created a new virtual environment
2) Used pip to install Tensorflow (1.13.0rc2), numpy (1.16.1), PyQT5 (5.12), PyAML (3.13) and opencv-python (4.0.0.21) in the virtual environment
3) Downloaded code and model
4) Created folder "ckpt" within the "SC-FEGAN-master" folder and placed the model there

Now, if I run:
`(venv) C:\WINDOWS\system32>python C:\Users\Jan\Downloads\SC-FEGAN-master\demo.py`

I get:
 
>  File "C:\Users\Jan\Downloads\SC-FEGAN-master\demo.py", line 229, in <module>
    config = Config('demo.yaml')
  File "C:\Users\Jan\Downloads\SC-FEGAN-master\utils\config.py", line 10, in __init__
    assert os.path.exists(filename), "ERROR: Config File doesn't exist."
AssertionError: ERROR: Config File doesn't exist.`>

If I run:
`(venv) C:\WINDOWS\system32>python C:\Users\Jan\Downloads\SC-FEGAN-master\ui\ui.py`

I get:

> Traceback (most recent call last):
  File "C:\Users\Jan\Downloads\SC-FEGAN-master\ui\ui.py", line 84, in <module>
    ui.setupUi(Form)
  File "C:\Users\Jan\Downloads\SC-FEGAN-master\ui\ui.py", line 47, in setupUi
    self.pushButton.clicked.connect(Form.open)
AttributeError: 'QWidget' object has no attribute 'open' 

> 

Any idea what the problem could be?

**Comment by JoYoungjoo** [comment]
Hello, the message ' os.path.exists(filename), "ERROR: Config File doesn't exist." ' means that the system can't find the 'demo.yaml' file. Check the os.path function in your Python version.

And the ui.py file is automatically made by Qt designer. So, the main function in ui.py does not mean anything.
