### ISSUE TITLE
'QWidget' object has no attribute 'open'

### ISSUE THREAD

**Issue by Ulyev-ad** [JoYoungjoo/SC-FEGAN#12]
Hi! I want to test your neural network, but I'm getting a 48-line error. Installed all the dependencies, as in your manual. Python 3.6.7. PyQT 5.

File ui/ui.py, error:
`self.pushButton.clicked.connect(Form.open)`

**Comment by JoYoungjoo** [comment]
I think you run ui.py.
Do:
- $ python3 demo.py
