### ISSUE TITLE
issues about  Local signal normalization

### ISSUE THREAD

**Issue by liang233** [JoYoungjoo/SC-FEGAN#14]
hello,  in Style transfer and image restoration,instancenorm is often used ,why network uses local signal normalization？  thanks

**Comment by JoYoungjoo** [comment]
hello, liang233.
You mean LRN(Local Response Normalization)?
I think you want to know that why i used LRN instead of BIN(Batch-Instance Normalization).
If i am right, send me a email with details you want.

**Comment by PaTricksStar** [comment]
# @JoYoungjoo Same question.
Why LRN ?
Have you compared the performance of different normalizations (BN/IN/LRN) ?
Did not find any discussion in your paper. Looking forward to your reply.
