### ISSUE TITLE
Example do not start on CPU

### ISSUE THREAD

**Issue by spartedo** [JoYoungjoo/SC-FEGAN#15]
Can't start example:
```
root@ubuntu:~/experiment/SC-FEGAN-master# python3 demo.py
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from model import Model
  File "/root/experiment/SC-FEGAN-master/model.py", line 4, in <module>
    from ops import *
  File "/root/experiment/SC-FEGAN-master/ops.py", line 9
    """
      ^
SyntaxError: invalid syntax
```

I am running via CPU:
```
root@ubuntu:~/experiment/SC-FEGAN-master# cat demo.yaml
INPUT_SIZE: 512
BATCH_SIZE: 1

#GPU_NUM: 1

# directories
CKPT_DIR: './ckpt/SC-FEGAN.ckpt'
```

**Comment by spartedo** [comment]
I am running components version:
```
Ubuntu 18.04.2 LTS
Python 3.6.7
tensorflow (1.12.0)
numpy (1.16.1)
opencv-python (4.0.0.21)
PyYAML Version: 3.12
PyQt5 Version: 5.12
```

**Comment by anatoly-kor** [comment]
@spartedo I have the same problem. Try just to remove the multi-line comment in line 9 of file ops.py.

**Comment by vikasTmz** [comment]
Commenting out `GPU_NUM` to use cpu will return a KeyError in `SC-FEGAN/utils/config.py, line 21`. So just remove the number specified after `GPU_NUM`.

Then merge [this pr](https://github.com/JoYoungjoo/SC-FEGAN/pull/16#issue-256994476) to solve invalid syntax issue.

**Comment by spartedo** [comment]
Thank you, removing multiline comment and
```
GPU_NUM:
```
in demo.yaml helped me.
