### ISSUE TITLE
checkpoint not found

### ISSUE THREAD

**Issue by Venus24kk** [JoYoungjoo/SC-FEGAN#20]
Hi,
I downloaded the model and located in the correct position as you mentioned. However, I got this error when I run demo.py file.
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory ./ckpt

Where should I download it?
Please help me how to resolve this issue.
Thank you.

**Comment by MichealJl** [comment]
can you tell me how to resolve this issue
