### ISSUE TITLE
How to make sketch 

### ISSUE THREAD

**Issue by huangqianfirst** [JoYoungjoo/SC-FEGAN#24]
@JoYoungjoo 
Could you please tell some details about how to make sketch like below:
![image](https://user-images.githubusercontent.com/11473038/54180453-aa28c700-44d6-11e9-88d7-73b1b0da994f.png)
I used HED to make sketch after histogram equalization, but still can't get facial sketch.
![portrait_clahe_concat](https://user-images.githubusercontent.com/11473038/54180570-ea884500-44d6-11e9-9547-d9709c686e35.png)
Looking forward to your reply.

**Comment by JoYoungjoo** [comment]
Hello @huangqianfirst
I think you get some idea for getting facial sketch from https://github.com/phillipi/pix2pix.
Also, the method for histogram equalization shows different performance depends on image read library(opencv, pyImage).
In my case, i used CLAHE method for histogram equalization and read the image with PIL library.

**Comment by huxianer** [comment]
@JoYoungjoo Hi，Could you share the scripts of making datasets,TKS!

**Comment by donghaoye** [comment]
How to use CLAHE method for histogram equalization?

**Comment by tzt101** [comment]
Hi, does anyone get the currect sketch?

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2021-06-28T11:26:14
          
          
            * Subject : 
Re: [run-youngjoo/SC-FEGAN] How to make sketch (#24)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
