### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by yf0123** [JoYoungjoo/SC-FEGAN#55]
Could you please send me a complete code(including training code)?

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
jongyoul@etri.re.kr
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
jongyoul@etri.re.kr
          
          
            * Sent time : 
2020-12-17T21:17:05
          
          
            * Subject : 
[run-youngjoo/SC-FEGAN] training code (#55)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           dooray@nhn.com
        
    
  
  
    
        © Dooray!.

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
jongyoul@etri.re.kr
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
jongyoul@etri.re.kr
          
          
            * Sent time : 
2020-12-17T21:17:16
          
          
            * Subject : 
Re: [run-youngjoo/SC-FEGAN] training code (#55)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           dooray@nhn.com
        
    
  
  
    
        © Dooray!.
