### ISSUE TITLE
The color of the result is different？

### ISSUE THREAD

**Issue by watertianyi** [JoYoungjoo/SC-FEGAN#64]

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2022-11-11T11:11:21
          
          
            * Subject : 
[run-youngjoo/SC-FEGAN] The color of the result is different？ (Issue #64)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.

**Comment by JayJongyoul** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2022-11-11T16:48:28
          
          
            * Subject : 
Re: [run-youngjoo/SC-FEGAN] The color of the result is different？ (Issue #64)
          
          
            
              
                * Remote host said : 
              
              
                
Requested action not taken: mailbox unavailable
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
